services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Code202\Security\:
        resource: '../../'
        exclude:
            - '../../Attribute'
            - '../../Authenticator/'
            - '../../Bridge/'
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Event/'
            - '../../Exception/'
            - '../../Request/'
            - '../../Code202SecurityBundle.php'
